apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ack-namespaces-cache-athena-controller
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: ack-namespaces-cache-athena-controller
subjects:
- kind: ServiceAccount
  name: ack-athena-controller
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ack-configmaps-cache-athena-controller
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: ack-configmaps-cache-athena-controller
subjects:
- kind: ServiceAccount
  name: ack-athena-controller
  namespace: {{ .Release.Namespace }}