apiVersion: v1
name: athena-chart
description: A Helm chart for the ACK service controller for Amazon Athena (Athena)
version: 1.0.2
appVersion: 1.0.2
home: https://github.com/aws-controllers-k8s/athena-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/athena-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: Athena Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/athena-maintainer
keywords:
  - aws
  - kubernetes
  - athena
